name: SST Next.js Development Deployment Destruction

on:
  workflow_dispatch:

jobs:
  wreak-havoc-and-destruction:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Unlock and Destroy the deployment
      - name: Unlock and Destroy (Development)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          npx sst unlock --stage dev
          npx sst remove --stage dev
